/**
 * WebApp
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppointedOfficialDto } from './appointedOfficialDto';
import { ElectedOfficialDto } from './electedOfficialDto';


export interface GovbodyDetailsDto { 
    name?: string | null;
    parentLocationId?: number;
    electedOfficials?: Array<ElectedOfficialDto> | null;
    appointedOfficials?: Array<AppointedOfficialDto> | null;
    recordingsUrl?: string | null;
    transcriptsUrl?: string | null;
}

