/**
 * Govmeeting.api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GovlocTypes = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const GovlocTypes = {
    NUMBER_0: 0 as GovlocTypes,
    NUMBER_1: 1 as GovlocTypes,
    NUMBER_2: 2 as GovlocTypes,
    NUMBER_3: 3 as GovlocTypes,
    NUMBER_4: 4 as GovlocTypes,
    NUMBER_5: 5 as GovlocTypes,
    NUMBER_6: 6 as GovlocTypes,
    NUMBER_7: 7 as GovlocTypes
};

